version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "RobotDisco"
    commit-message:
      prefix: "chore"
    labels:
      - dependencies
      - automated
