keys:
  - &gaelan BE3878AD5D9790E8240DE128A815AC9D526EE85A
  - &arrakis 62378c2ba0acbec37f762be08bd4cb68d3656599
  - &chapterhouse df8dc97ad3fa47479d26009341fcff767ce6cdf4
  - &darktower 8e9d6bdac66dc0a406fa54a30f53dcc257407e7f
  - &kaitain e906898e53902a3505b74448df2bbade6e3de700
  - &salusa 4e86896c4c437c633c0111f6219badddfb4669c6
  - &salusa-old 230e31f798a23f94c4ea51b322fdeaaeec058fef
creation_rules:
  - path: secrets/common.json
    key_groups:
      - pgp:
          - *gaelan
          - *arrakis
          - *darktower
          - *kaitain
          - *chapterhouse
          - *salusa
          - *salusa-old
  - path: secrets/databases.json
    key_groups:
      - pgp:
          - *gaelan
          - *salusa
  - path: secrets/borg-chapterhouse.json
    key_groups:
      - pgp:
          - *gaelan
          - *chapterhouse
  - path: secrets/vaultwarden.yaml
    key_groups:
      - pgp:
          - *gaelan
          - *salusa
