keys:
  - &gaelan BE3878AD5D9790E8240DE128A815AC9D526EE85A
  - &arrakis 62378c2ba0acbec37f762be08bd4cb68d3656599
creation_rules:
  - path: secrets/common.json
    key_groups:
      - pgp:
          - *gaelan
          - *arrakis
