(source gnu)
(source melpa)

(depends-on "ack-and-a-half")
(depends-on "cask")
(depends-on "magit")
(depends-on "projectile")
(depends-on "smex")
(depends-on "cyberpunk-theme")
(depends-on "flx-ido")
(depends-on "rainbow-delimiters")
(depends-on "smartparens")
(depends-on "flycheck")
(depends-on "rainbow-mode")
(depends-on "feature-mode")
(depends-on "jedi")
(depends-on "exec-path-from-shell")
