# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/rootpool";
      fsType = "btrfs";
      options = [ "subvol=@root" "compress=zstd" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-label/rootpool";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-label/rootpool";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/var/lib" =
    { device = "/dev/disk/by-label/rootpool";
      fsType = "btrfs";
      options = [ "subvol=@varlib" "compress=zstd" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-label/rootpool";
      fsType = "btrfs";
      options = [ "subvol=@varlog" "compress=zstd" "noatime" ];
    };

  fileSystems."/var/spool/mail" =
    { device = "/dev/disk/by-label/rootpool";
      fsType = "btrfs";
      options = [ "subvol=@varmail" "compress=zstd" "relatime" ];
    };

  fileSystems."/boot0" =
    { device = "/dev/disk/by-label/EFIBOOT0";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" "noatime" ];
    };

  fileSystems."/boot1" =
    { device = "/dev/disk/by-label/EFIBOOT1";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" "noatime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-label/swappart0"; }
      { device = "/dev/disk/by-label/swappart1"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0f1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
