#### FILENAME: zshenv
#### AUTHOR: Gaelan D'costa (gdcosta@gmail.com)
#### LICENSE: https://opensource.org/licenses/GPL-3.0
#### DESCRIPTION: Foundational environment settings

### XDG Base Directory Specification
### http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export ZSH_CONFIG="$XDG_CONFIG_HOME/zsh"
export ZSH_CACHE="$XDG_CACHE_HOME/zsh"

### executable search paths
export PATH=$PATH:$HOME/bin

### activate local nix install if required
### This is needed early because this fundamentally is
### how we locally customize our system.
if [[ -f ~/.nix-profile/etc/profile.d/nix.sh ]]; then
    source ~/.nix-profile/etc/profile.d/nix.sh
fi
