#### FILENAME: zshenv
#### AUTHOR: Gaelan D'costa (gdcosta@gmail.com)
#### LICENSE: https://opensource.org/licenses/GPL-3.0
#### DESCRIPTION: Foundational environment settings

### XDG Base Directory Specification
### http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export ZSH_CONFIG="$XDG_CONFIG_HOME/zsh"
export ZSH_CACHE="$XDG_CACHE_HOME/zsh"

# Golang dev environment
export GOPATH=$HOME/code/go

### executable search paths
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$GOPATH/bin


