#### FILENAME: zshrc
#### Author: Gaelan D'costa (gdcosta@gmail.com)
#### LICENSE: https://opensource.org/licenses/GPL-3.0
####
#### DESCRIPTION: Configuration that applies to interactive sessions
#### THANKS: https://github.com/seebi/zshrc for the layout inspiration

### ZSH modules

## This array holds the list of zsh modules I have written and want to load.
typeset -ga gaelan_zsh_modules

## user aliases
gaelan_zsh_modules+="$ZSH_CONFIG/aliases.zsh"
## tab completion
gaelan_zsh_modules+="$ZSH_CONFIG/completion.zsh"
## fasd, the fuzzy file/directory finder
gaelan_zsh_modules+="$ZSH_CONFIG/fasd.zsh"

## zsh customiztions
gaelan_zsh_modules+="$ZSH_CONFIG/options.zsh"
gaelan_zsh_modules+="$ZSH_CONFIG/prompt.zsh"

## Check for a system specific file
systemFile=`uname -s | tr "[:upper:]" "[:lower:]"`
gaelan_zsh_modules+="$ZSH_CONFIG/$systemFile.zsh"

## SSH (specifically, ssh key management)
gaelan_zsh_modules+="$ZSH_CONFIG/ssh.zsh"

## customizations for work
gaelan_zsh_modules+="$ZSH_CONFIG/work_tulip.zsh"


## load all modules, failing gracefully if not found
foreach file (`echo $gaelan_zsh_modules`)
if [[ -a $file ]]; then
    source $file
fi
end

## Make ZSH use the good parts of FISH
if [[ `uname` == 'Darwin' ]]; then
    fpath=(/usr/local/share/zsh-completions $fpath)
    source "/usr/local/opt/zsh-git-prompt/zshrc.sh"
    source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
    # Fish-like syntax highlighting. Must be at the end of .zshrc
    source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    # Fish-like history substring search. Must be at the end of the .zshrc
    source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
else
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
    # Fish-like syntax highlighting. Must be at the end of .zshrc
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi
