#### FILENAME: zshrc
#### Author: Gaelan D'costa (gdcosta@gmail.com)
#### LICENSE: https://opensource.org/licenses/GPL-3.0
####
#### DESCRIPTION: Configuration that applies to interactive sessions
#### THANKS: https://github.com/seebi/zshrc for the layout inspiration

### ZSH modules

## This array holds the list of zsh modules I have written and want to load.
typeset -ga gaelan_zsh_modules

## user aliases
gaelan_zsh_modules+="$ZSH_CONFIG/aliases.zsh"
## tab completion
gaelan_zsh_modules+="$ZSH_CONFIG/completion.zsh"
## fasd, the fuzzy file/directory finder
gaelan_zsh_modules+="$ZSH_CONFIG/fasd.zsh"

# zsh customiztions
gaelan_zsh_modules+="$ZSH_CONFIG/options.zsh"
gaelan_zsh_modules+="$ZSH_CONFIG/prompt.zsh"


## load all modules, failing gracefully if not found
foreach file (`echo $gaelan_zsh_modules`)
if [[ -a $file ]]; then
    source $file
fi
end

export XKB_DEFAULT_OPTIONS=ctrl:nocaps

# Include tdocker into PATH
if [ -d ~/workspace/dev_scripts/docker/bin ]; then
   export PATH=$PATH:~/workspace/dev_scripts/docker/bin
fi

# Activate rbenv and pyenv
command -v rbenv >/dev/null 2>&1 && eval "$(rbenv init -)"
command -v pyenv >/dev/null 2>&1 && eval "$(pyenv init -)"

# activate NVM if it's available
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

if [[ `uname` == 'Darwin' ]]; then
   SSH_KEYS="id_rsa"
else
   SSH_KEYS="id_rsa id_rsa.work"
fi
command -v keychain >/dev/null 2>&1 && eval "$(keychain --quiet --agents ssh --eval $=SSH_KEYS)"

## Make ZSH use the good parts of FISH
if [[ `uname` == 'Darwin' ]]; then
    fpath=(/usr/local/share/zsh-completions $fpath)
    source "/usr/local/opt/zsh-git-prompt/zshrc.sh"
    source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
    # Fish-like syntax highlighting. Must be at the end of .zshrc
    source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    # Fish-like history substring search. Must be at the end of the .zshrc
    source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
else
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
    # Fish-like syntax highlighting. Must be at the end of .zshrc
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi


if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
  exec startx
fi
