#### FILENAME: zshrc
#### Author: Gaelan D'costa (gdcosta@gmail.com)
#### LICENSE: https://opensource.org/licenses/GPL-3.0
####
#### DESCRIPTION: Configuration that applies to interactive sessions
#### THANKS: https://github.com/seebi/zshrc for the layout inspiration

### ZSH modules

## This array holds the list of zsh modules I have written and want to load.
typeset -ga gaelan_zsh_modules

## user aliases
gaelan_zsh_modules+="$ZSH_CONFIG/aliases.zsh"
## tab completion
gaelan_zsh_modules+="$ZSH_CONFIG/completion.zsh"
## fasd, the fuzzy file/directory finder
gaelan_zsh_modules+="$ZSH_CONFIG/fasd.zsh"

## zsh customiztions
gaelan_zsh_modules+="$ZSH_CONFIG/options.zsh"
gaelan_zsh_modules+="$ZSH_CONFIG/prompt.zsh"

## Check for a system specific file
systemFile=`uname -s | tr "[:upper:]" "[:lower:]"`
gaelan_zsh_modules+="$ZSH_CONFIG/$systemFile.zsh"

## SSH (specifically, ssh key management)
gaelan_zsh_modules+="$ZSH_CONFIG/ssh.zsh"

## customizations for work
gaelan_zsh_modules+="$ZSH_CONFIG/work_tulip.zsh"

## adding ZSH plugins via submodules
gaelan_zsh_modules+="$ZSH_CONFIG/zsh-autosuggestions/zsh-autosuggestions.zsh"
gaelan_zsh_modules+="$ZSH_CONFIG/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
gaelan_zsh_modules+="$ZSH_CONFIG/zsh-history-substring-search/zsh-history-substring-search.zsh"


## load all modules, failing gracefully if not found
foreach file (`echo $gaelan_zsh_modules`)
if [[ -a $file ]]; then
    source $file
fi
end
[ -f "${GHCUP_INSTALL_BASE_PREFIX:=$HOME}/.ghcup/env" ] && source "${GHCUP_INSTALL_BASE_PREFIX:=$HOME}/.ghcup/env"
