#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# run all system-supplied xinit hooks
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
	[ -x "$f" ] && . "$f"
    done
    unset f
fi

# Disable access control for the current user.
xhost +SI:localhost:$USER

# Make Java applications aware this is a non-reparenting window manager.
export _JAVA_AWT_WM_NONREPARENTING=1

# Set default cursor.
xsetroot -cursor_name left_ptr

# CapsLock -> Ctrl
setxkbmap -model pc104 -option 'ctrl:nocaps'

# Start redshift (dim screen as sky gets darker)
redshift &
# Display important info (wifi connection, date, time, battery) in a persistent way.
while true; do
    echo \
        $(nmcli -t -f name connection show --active) \
        ' ' \
        $(date '+%F %H:%M') \
        ' ' \
        $(cat /sys/class/power_supply/BAT0/capacity)
    sleep 5
done | dzen2 -xs 0 -p -ta r -dock &
# Launch window manager
exec emacs
