export XKB_DEFAULT_OPTIONS=ctrl:nocaps
export PS1='[\u@\h \W]$ '

# Enable ZSH prompt
autoload -Uz promptinit
promptinit
prompt redhat

# Enable Command completion
autoload -Uz compinit
compinit
# Menu-style completion interface
zstyle ':completion:*' menu select

# Emacs is my editor
export GIT_EDITOR="emacsclient --alternate-editor=''"
export VISUAL="$GIT_EDITOR -n"
alias killemacs="emacsclient -e '(kill-emacs)'"

# If vim doesn't exist, invoke vi instead
command -v vim --help >/dev/null 2>&1 || alias vim=vi

# Command history
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history
setopt append_history
setopt extended_history
setopt hist_ignore_dups
setopt hist_expire_dups_first

# Include ~/bin in PATH
if [ -d ~/bin ]; then
    export PATH=$PATH:~/bin
fi

# Set Go root directory
export GOPATH=$HOME/code/go

# Add Go root to path
export PATH=$PATH:$GOPATH/bin

# Include Go toolchain in path
if [ -d /usr/local/opt/go/libexec/bin ]; then
    export PATH=$PATH:/usr/local/opt/go/libexec/bin
fi

# FASD aliases
alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection

# Helpers for editing/refreshing .zshrc
alias ezr='e ~/.zshrc'
alias ezp='e ~/.zprofile'
alias rzr='source ~/.zshrc'
alias rzp='source ~/.zprofile'

# Activate FASD
command -v fasd >/dev/null 2>&1 && eval "$(fasd --init auto)"

# Activate rbenv and pyenv
command -v rbenv >/dev/null 2>&1 && eval "$(rbenv init -)"
command -v pyenv >/dev/null 2>&1 && eval "$(pyenv init -)"

## Make ZSH use the good parts of FISH
if [[ `uname` == 'Darwin' ]]; then
    source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
    # Fish-like syntax highlighting. Must be at the end of .zshrc
    source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
else
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
    # Fish-like syntax highlighting. Must be at the end of .zshrc
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# activate NVM if it's available
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

if [[ `uname` == 'Darwin' ]]; then
   SSH_KEYS="id_rsa"
else
   SSH_KEYS="id_rsa id_rsa.work"
fi
command -v keychain >/dev/null 2>&1 && eval "$(keychain --quiet --agents ssh --eval $=SSH_KEYS)"

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
  exec startx
fi
