export XKB_DEFAULT_OPTIONS=ctrl:nocaps
export PS1='[\u@\h \W]$ '

if [[ `uname` == 'Darwin' ]]; then
   SSH_KEYS="id_rsa 674E1FC171DDC73E3217C844E8F9D7F62537F60E"
else
   SSH_KEYS="id_rsa id_rsa.work 60784A04C41ABCC22E3A04360F995EBCE3FA0AE8"
fi
command -v keychain >/dev/null 2>&1 && eval "$(keychain --quiet --agents gpg,ssh --eval $=SSH_KEYS)"

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
#  exec sway
  exec startx
fi
