export XKB_DEFAULT_OPTIONS=ctrl:nocaps
export PS1='[\u@\h \W]$ '

if [[ `uname` == 'Darwin' ]]; then
   SSH_KEYS="id_rsa"
else
   SSH_KEYS="id_rsa id_rsa.work"
fi
command -v keychain >/dev/null 2>&1 && eval "$(keychain --quiet --agents ssh --eval $=SSH_KEYS)"

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
#  exec sway
  exec startx
fi
