# Created by newuser for 5.3.1

# Enable Command completion
autoload -Uz compinit
compinit
# Menu-style completion interface
zstyle ':completion:*' menu select


# Enable ZSH prompt
autoload -Uz promptinit
promptinit
prompt redhat

# Emacs is my editor
export EDITOR='emacsclient --alternate-editor='' -c $@'
alias e=$EDITOR

# If vim doesn't exist, invoke vi instead
command -v vim --help >/dev/null 2>&1 || alias vim=vi

# Command history
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history
setopt append_history
setopt extended_history
setopt hist_ignore_dups
setopt hist_expire_dups_first

# Include ~/bin in PATH
if [ -d ~/bin ]; then
    export PATH=$PATH:~/bin
fi

# FASD aliases
alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection

# Helpers for editing/refreshing .zshrc
alias erc='e ~/.zshrc'
alias rrc='source ~/.zshrc'

# Activate FASD
command -v fasd >/dev/null 2>&1 && eval "$(fasd --init auto)"

# Activate rbenv and pyenv
command -v rbenv >/dev/null 2>&1 && eval "$(rbenv init -)"
command -v pyenv >/dev/null 2>&1 && eval "$(pyenv init -)"

## Make ZSH use the good parts of FISH
if [[ `uname` == 'Darwin' ]]; then
    source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
    # Fish-like syntax highlighting. Must be at the end of .zshrc
    source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
else
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
    # Fish-like syntax highlighting. Must be at the end of .zshrc
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh
