[default]
base-url = tulip.okta.com
username = gaelan@tulip.com
duration = 14400
app-link = https://tulip.okta.com/home/amazon_aws/0oa6h9ji70dvt6G4M5d7/272
role = arn:aws-cn:iam::004493658315:role/Okta-Admin

[awsusa]
profile = awsusa
app-link = https://tulip.okta.com/app/amazon_aws/exk3pwmuolwADDkn75d7/sso/saml
role = arn:aws:iam::991815424517:role/Okta-Admin

[awscn]
profile = awscn
app-link = https://tulip.okta.com/app/amazon_aws/exk6h9ji6z5PRTTUN5d7/sso/saml
role = arn:aws-cn:iam::004493658315:role/Okta-Admin
base-url = tulip.okta.com

