name: "Publish every Git push to trunk to FlakeHub"
on:
  push:
    branches:
      - "trunk"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "DeterminateSystems/nix-installer-action@v7"
      - uses: "DeterminateSystems/flakehub-push@v3"
        with:
          name: "RobotDisco/nix-config"
          rolling: true
          visibility: "public"
