name: push-to-cachix
on:
  push:
    branches:
    - 'trunk'

jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-22.11
      - name: Publish to cachix
        uses: cachix/cachix-action@v12
        with:
          name: robot-disco
          signingKey: ${{ secrets.CACHIX_KEY }}
