name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00 UTC

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v27
        with:
          commit-msg: "chore: Update flake.lock to latest inputs"
          pr-title: "chore: Update flake.lock to latest inputs" # Title of PR to be created.
          pr-labels: | # Labels to be set on the PR
            dependencies
            automated
          pr-assignees: RobotDisco
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
